### ISSUE TITLE
Have to kill -9

### ISSUE THREAD

**Issue by horse-latitudes** [antoniocarelli/Conky#1]
Hi.
I love this conky.conf but the only way I can stop it running is kill -9 it. Is there a more civilized way to exit?
This on Ubuntu 16.04.2 Unity
Any help appreciated.
Cheers Phil.

**Comment by antoniocarelli** [comment]
Hi Phil!
Thanks for using my conky.conf!
The only way to close conky is killing the process. But I used just kill, without sudo or 9 parameter...
Please try it that way.

**Comment by horse-latitudes** [comment]
Hi Antonio!
Thanks for that. Just kill is far kinder. Lovely!
