### ISSUE TITLE
Can't display correctly.

### ISSUE THREAD

**Issue by not-null-nil** [antoniocarelli/conky#1]
I just copied your configuration, but it doesn't work like what you posted. 
![screenshot_2017-11-09_21-23-56](https://user-images.githubusercontent.com/23580174/32607667-ad2f54fe-c594-11e7-9009-eec34e74f809.png)
I'm using Debian 9, please tell me what should I do?

**Comment by not-null-nil** [comment]
I have found the problem, sorry for that.

**Comment by not-null-nil** [comment]
Sorry again, but it seems  don't work after I power up the laptop in just three seconds, what should I do?

**Comment by antoniocarelli** [comment]
It's missing the installation of the font:
[Conky Icons by Carelli](https://github.com/antoniocarelli/conky/blob/master/Conky%20Icons%20by%20Carelli.ttf)
