### ISSUE TITLE
I don't understand how to reference icons

### ISSUE THREAD

**Issue by isuzufan** [antoniocarelli/conky#2]
EDIT:   Never mind!  I was able to find what I needed in another forum. Thanks anyway!

Hi!  I hope this is the right place to ask you this question. 

I saw your conky config file and am using it to help me with my own config file.  When you reference an icon you use odd characters that don't appear on my keyboard.  Can you tell me which keys correspond to which icons and how I can create those characters?  

Thank you!

**Comment by fralychen** [comment]
the seame I do.and I got another promblerm 
`conky: llua_do_call: function conky_main execution failed: attempt to call a nil value
conky: llua_do_call: function conky_main execution failed: attempt to call a nil value
conky: llua_do_call: function conky_main execution failed: attempt to call a nil value
conky: llua_do_call: function conky_main execution failed: attempt to call a nil value`

**Comment by antoniocarelli** [comment]
I'm away from my personal computer now, but I'll try to help.
On the end of conky_carelli_Painel.conf file, you need to set the correct path for the lua configuration file:

> lua_load = '~/Downloads/Temas/Conky/Conky_Git/Painel/conky_carelli_Painel.lua',

**Comment by antoniocarelli** [comment]
On this site: https://fontdrop.info/ you can see all de caracters from my font, just droping the file on it.

**Comment by antoniocarelli** [comment]
Can you run this commands and post back the result?
$`conky -v`
$`lua -v`

**Comment by fralychen** [comment]
I‘m away from my personal computer now,The lua version like 5.0+  and conky do not know.

**Comment by fralychen** [comment]
lua_load path is to my conky_carelli_Painel.lua's path

**Comment by antoniocarelli** [comment]
> I‘m away from my personal computer now,The lua version like 5.0+ and conky do not know.

Can you tell if lua package for conky is installed? You can see it with conky -v command:

```
conky 1.10.8 compiled Thu May  3 21:07:47 UTC 2018 for Linux 4.4.0-122-generic x86_64
Compiled in features:
System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky

 General:
  * math
...

 Lua bindings:
  * Cairo
  * Imlib2
  * RSVG
...
 ```

**Comment by fralychen** [comment]
`conky 1.11.4_pre compiled Sun 30 Jun 2019 11:54:36 AM UTC for Linux 5.1.15-1-MANJARO x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky


 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * wireless
  * support for IBM/Lenovo notebooks
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * OSS mixer support
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
  * PulseAudio
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * Xshape extension (click through)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * CMUS
  * MPD
  * MOC

 Default values:
  * Netdevice: eno1
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 256
  * Maximum text size: 16384
  * Size text buffer: 256
`
`lua -v
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
`

**Comment by fralychen** [comment]
can you add the setup to read.me file, may can to help more people.

**Comment by antoniocarelli** [comment]
I don't know what's going on with your setup, becose on my instalaton, every thing is going ok.

The two commom problems is with the path and with the concky instalation. So you can try to install conky-all.

If it not work, I don't know what to try more.

**Comment by antoniocarelli** [comment]
I don't know what's going on with your setup, becose on my instalaton, every thing is going ok.

The two commom problems is with the path and with the concky instalation. So you can try to install conky-all.

If it not work, I don't know what to try more.

**Comment by antoniocarelli** [comment]
If it not work, I don't know what to try more.
